
[[caldav-extensions]]
== CalDAV Extensions

This specification extends <<RFC4791>> in that it defines a new
component and new iCalendar properties to be supported and requires
extra definitions related to time-ranges and reports.

Additionally, it extends <<RFC6638>> as it a VPOLL component is a
schedulable entity.

=== Calendar Collection Properties

This section defines new CalDAV properties for calendar collections.

==== CALDAV:supported-vpoll-component-sets

Name:: supported-vpoll-component-sets

Namespace:: urn:ietf:params:xml:ns:caldav

Purpose:: Specifies the calendar component types (e.g., VEVENT,
  VTODO, etc.) and combination of types that may be included in a
  VPOLL component.

Conformance:: This property MAY be defined on any calendar
  collection.  If defined, it MUST be protected and SHOULD NOT be
  returned by a PROPFIND DAV:allprop request (as defined in
  <<RFC2518,section=12.14.1>>).

Description:: The CALDAV:supported-vpoll-component-sets property is
used to specify restrictions on the calendar component types that
VPOLL components may contain in a calendar collection. +
+
It also specifies the combination of allowed component types. +
+
Any attempt by the client to store VPOLL components with component
types or combinations of types not listed in this property, if it
exists, MUST result in an error, with the `CALDAV:supported-vpoll-component-sets`
precondition <<caldav-additional-preconditions>> being violated.  Since
this property is protected, it cannot be changed by clients using
a PROPPATCH request.  However, clients can initialize the value of
this property when creating a new calendar collection with
MKCALENDAR.  In the absence of this property, the server MUST
accept all component types, and the client can assume that all
component types are accepted.

Definition::
[source]
----
<!ELEMENT supported-vpoll-component-sets
     (supported-vpoll-component-set*) >

<!ELEMENT supported-vpoll-component-set (comp+)>
----

[example]
[source,xml]
----
<C:supported-vpoll-component-sets
     xmlns:C="urn:ietf:params:xml:ns:caldav">

  <!-- VPOLLs with VEVENT, VFREEBUSY or VTODO -->
  <C:supported-vpoll-component-set>
    <C:comp name="VEVENT" />
    <C:comp name="VFREEBUSY" />
    <C:comp name="VTODO" />
  </C:supported-vpoll-component-set>

  <!-- VPOLLs with just VEVENT or VFREEBUSY -->
  <C:supported-vpoll-component-set>
    <C:comp name="VEVENT" />
    <C:comp name="VFREEBUSY" />
  </C:supported-vpoll-component-set>

  <!-- VPOLLs with just VEVENT -->
  <C:supported-vpoll-component-set>
    <C:comp name="VEVENT" />
  </C:supported-vpoll-component-set>

  <!-- VPOLLs with just VTODO -->
  <C:supported-vpoll-component-set>
    <C:comp name="VTODO" />
  </C:supported-vpoll-component-set>
</C:supported-vpoll-component-sets>
----

[[vpoll-max-items]]
==== CALDAV:vpoll-max-items

Name:: vpoll-max-items

Namespace:: urn:ietf:params:xml:ns:caldav

Purpose:: Provides a numeric value indicating the maximum number of
  items that may be contained in any instance of a VPOLL calendar
  object resource stored in the calendar collection.

Conformance:: This property MAY be defined on any calendar
  collection.  If defined, it MUST be protected and SHOULD NOT be
  returned by a PROPFIND DAV:allprop request (as defined in
  <<RFC2518,section=12.14.1>>).

Description:: The CALDAV:vpoll-max-items is used to specify a numeric
  value that indicates the maximum number of iCalendar components in
  any one instance of a VPOLL calendar object resource stored in a
  calendar collection.  Any attempt to store a calendar object
  resource with more components per instance than this value MUST
  result in an error, with the CALDAV: vpoll-max-items precondition
  <<caldav-additional-preconditions>> being violated.  In the absence of this property, the
  client can assume that the server can handle any number of items
  in a VPOLL calendar component.

Definition::
[source]
----
<!ELEMENT vpoll-max-items (#PCDATA)>
PCDATA value: a numeric value (integer greater than zero)
----

[example]
[source,xml]
----
<C:vpoll-max-items xmlns:C="urn:ietf:params:xml:ns:caldav"
>25</C:vpoll-max-items>
----

[[vpoll-max-active]]
==== CALDAV:vpoll-max-active

Name:: vpoll-max-active

Namespace:: urn:ietf:params:xml:ns:caldav

Purpose:: Provides a numeric value indicating the maximum number of
  active vpolls at any one time.

Conformance:: This property MAY be defined on any calendar
  collection.  If defined, it MUST be protected and SHOULD NOT be
  returned by a PROPFIND DAV:allprop request (as defined in
  <<RFC2518,section=12.14.1>>).

Description:: The CALDAV:vpoll-max-active is used to specify a
  numeric value that indicates the maximum number of active VPOLLs
  at any one time.  Any attempt to store a new active VPOLL calendar
  object resource which results in exceeding this limit MUST result
  in an error, with the `CALDAV:vpoll-max-active` precondition
  <<caldav-additional-preconditions>> being violated.  In the absence of this property, the
  client can assume that the server can handle any number of active
  VPOLLs.

Definition::
[source]
----
<!ELEMENT vpoll-max-active (#PCDATA)>
PCDATA value: a numeric value (integer greater than zero)
----

[example]
[source,xml]
----
<C:vpoll-max-active xmlns:C="urn:ietf:params:xml:ns:caldav"
>25</C:vpoll-max-active>
----

[[vpoll-max-voters]]
==== CALDAV:vpoll-max-voters

Name:: `vpoll-max-voters`

Namespace:: `urn:ietf:params:xml:ns:caldav`

Purpose:: Provides a numeric value indicating the maximum number of
  voters for any instance of a VPOLL calendar object resource stored
  in the calendar collection.

Conformance:: This property MAY be defined on any calendar
  collection.  If defined, it MUST be protected and SHOULD NOT be
  returned by a PROPFIND `DAV:allprop` request (as defined in
  <<RFC2518,section=12.14.1>>).

Description:: The `CALDAV:vpoll-max-voters` is used to specify a
  numeric value that indicates the maximum number of voters for any one instance of a VPOLL calendar object
  resource stored in a calendar collection. Any attempt to store a
  calendar object resource with more voters per instance
  than this value MUST result in an error, with the CALDAV:
  `vpoll-max-voters` precondition <<caldav-additional-preconditions>>
  being violated.  In the absence of this property, the client can
  assume that the server can handle any number of voters in a VPOLL
  calendar component.

Definition::
[source]
----
<!ELEMENT vpoll-max-voters (#PCDATA)>
PCDATA value: a numeric value (integer greater than zero)
----

[example]
[source,xml]
----
<C:vpoll-max-voters xmlns:C="urn:ietf:params:xml:ns:caldav"
>25</C:vpoll-max-voters>
----

==== CalDAV:even-more-properties

// TODO: vpoll-supported-mode poll options - e.g "vpoll-basic"


==== Extensions to CalDAV scheduling

This specification extends <<RFC6638>>.

Each section of Appendix A "Scheduling Privileges Summary" is
extended to include VPOLL.

Any reference to the ATTENDEE property should be read to include the
CALENDAR-ADDRESS property contained in the PARTICIPANT compoents.
That is, for scheduling purposes the CALENDAR-ADDRESS property
is handled in exactly the same manner as the ATTENDEE property.

[[caldav-additional-preconditions]]
=== Additional Preconditions for PUT, COPY, and MOVE

This specification creates additional Preconditions for PUT, COPY,
and MOVE methods.  These preconditions apply when a PUT operation of
a VPOLL calendar object resource into a calendar collection occurs,
or when a COPY or MOVE operation of a calendar object resource into a
calendar collection occurs, or when a COPY or MOVE operation occurs
on a calendar collection.

The new preconditions are:

(CALDAV:supported-vpoll-component-sets):: The VPOLL resource
  submitted in the PUT request, or targeted by a COPY or MOVE
  request, MUST contain a type or combination of calendar component
  that is supported in the targeted calendar collection;

(CALDAV:vpoll-max-items):: The VPOLL resource submitted in the PUT
  request, or targeted by a COPY or MOVE request, MUST have a number
  of sub-components (excluding VTIMEZONE) less than or equal to the
  value of the `CALDAV:vpoll-max-items` property value <<vpoll-max-items>>
  on the calendar collection where the resource will be stored;

(CALDAV:vpoll-max-active):: The PUT request, or COPY or MOVE request,
  MUST not result in the number of active VPOLLs being greater than
  the value of the `CALDAV:vpoll-max-active` property value
  <<vpoll-max-active>> on the calendar collection where the resource will
  be stored;

(CALDAV:vpoll-max-voters):: The VPOLL resource submitted in the PUT
  request, or targeted by a COPY or MOVE request, MUST have a number
  of voters represented by PARTICIPANT components less than or equal to the value of the
  `CALDAV:vpoll-max-voters` property value <<vpoll-max-voters>> on the
  calendar collection where the resource will be stored;

=== CalDAV:calendar-query Report

This allows the retrieval of VPOLLs and their included components.
The query specification allows queries to be directed at the
contained sub-components.  For VPOLL queries this feature is
disallowed.  Time-range queries can only target the vpoll component
itself.

==== Example: Partial Retrieval of VPOLL

In this example, the client requests the server to return specific
components and properties of the VPOLL components that overlap the
time range from December 4, 2012, at 00:00:00 A.M.  UTC to December
5, 2012, at 00:00:00 A.M.  UTC.  In addition, the `DAV:getetag`
property is also requested and returned as part of the response.
Note that due to the CALDAV: calendar-data element restrictions, the
DTSTAMP property in VPOLL components has not been returned, and the
only property returned in the VCALENDAR object is VERSION.

[source]
----
>> Request <<

REPORT /cyrus/work/ HTTP/1.1
Host: cal.example.com
Depth: 1
Content-Type: application/xml; charset="utf-8"
Content-Length: xxxx

<?xml version="1.0" encoding="utf-8" ?>
<C:calendar-query xmlns:D="DAV:"
              xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <D:getetag/>
    <C:calendar-data>
      <C:comp name="VCALENDAR">
        <C:prop name="VERSION"/>
        <C:comp name="VPOLL">
          <C:prop name="SUMMARY"/>
          <C:prop name="UID"/>
          <C:prop name="DTSTART"/>
          <C:prop name="DTEND"/>
          <C:prop name="DURATION"/>
        </C:comp>

      </C:comp>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VPOLL">
        <C:time-range start="20121204T000000Z"
                      end="20121205T000000Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

>> Response <<

HTTP/1.1 207 Multi-Status
Date: Sat, 11 Nov 2012 09:32:12 GMT
Content-Type: application/xml; charset="utf-8"
Content-Length: xxxx

<?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:"
           xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:response>
    <D:href>http://cal.example.com/cyrus/work/poll2.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>"fffff-abcd2"</D:getetag>
        <C:calendar-data>BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VPOLL
DTSTART;TZID=US/Eastern:20121202T120000
DURATION:PT4D
SUMMARY:Poll #2
UID:00959BC664CA650E933C892C@example.com
END:VPOLL
END:VCALENDAR
</C:calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>http://cal.example.com/cyrus/work/poll3.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>"fffff-abcd3"</D:getetag>
        <C:calendar-data>BEGIN:VCALENDAR

VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VPOLL
DTSTART;TZID=US/Eastern:20121204T100000
DURATION:PT4D
SUMMARY:Poll #3
UID:DC6C50A017428C5216A2F1CD@example.com
END:VPOLL
END:VCALENDAR
</C:calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
----

=== CalDAV time ranges

"CALDAV:time-range XML Element" in <<RFC4791,section=9.9>> describes
how to specify time ranges to limit the set of calendar components
returned by the server.  This specification extends <<RFC4791>> to
describe the meaning of time ranges for VPOLL

A VPOLL component is said to overlap a given time range if the
condition for the corresponding component state specified in the
table below is satisfied.  The conditions depend on the presence of
the DTSTART, DURATION, DTEND, COMPLETED and CREATED properties in the
VPOLL component.  Note that, as specified above, the DTEND value MUST
be a DATE-TIME value equal to or after the DTSTART value if
specified.

----
+-------------------------------------------------------------------+
| VPOLL has the DTSTART property?                                   |
|   +---------------------------------------------------------------+
|   |   VPOLL has the DURATION property?                            |
|   |   +-----------------------------------------------------------+
|   |   | VPOLL has the DTEND property?                             |
|   |   |   +-------------------------------------------------------+
|   |   |   | VPOLL has the COMPLETED property?                     |
|   |   |   |   +---------------------------------------------------+
|   |   |   |   | VPOLL has the CREATED property?                   |
|   |   |   |   |   +-----------------------------------------------+
|   |   |   |   |   | Condition to evaluate                         |
+---+---+---+---+---+-----------------------------------------------+
| Y | Y | N | * | * | (start  <= DTSTART+DURATION)  AND             |
|   |   |   |   |   | ((end   >  DTSTART)  OR                       |
|   |   |   |   |   |  (end   >= DTSTART+DURATION))                 |
+---+---+---+---+---+-----------------------------------------------+
| Y | N | Y | * | * | ((start <  DTEND)    OR  (start <= DTSTART))  |
|   |   |   |   |   | AND                                           |
|   |   |   |   |   | ((end   >  DTSTART)  OR  (end   >= DTEND))    |
+---+---+---+---+---+-----------------------------------------------+
| Y | N | N | * | * | (start  <= DTSTART)  AND (end >  DTSTART)     |
+---+---+---+---+---+-----------------------------------------------+
| N | N | Y | * | * | (start  <  DTEND)    AND (end >= DTEND)       |
+---+---+---+---+---+-----------------------------------------------+
| N | N | N | Y | Y | ((start <= CREATED)  OR  (start <= COMPLETED))|
|   |   |   |   |   | AND                                           |
|   |   |   |   |   | ((end   >= CREATED)  OR  (end   >= COMPLETED))|
+---+---+---+---+---+-----------------------------------------------+
| N | N | N | Y | N | (start  <= COMPLETED) AND (end  >= COMPLETED) |
+---+---+---+---+---+-----------------------------------------------+
| N | N | N | N | Y | (end    >  CREATED)                           |
+---+---+---+---+---+-----------------------------------------------+
| N | N | N | N | N | TRUE                                          |
+---+---+---+---+---+-----------------------------------------------+
----

