[[itip-with-participants]]
== iTip With Participants

The PARTICIPANT component introduced in <<RFC9073>> with the addition of some properties defined in this specification mirrors the participant object in <<RFC8984>>.

For all existing schedulable and publishable components, VEVENT, VTODO, VFREEBUSY, and VAVAILABILITY; the ORGANIZER and ATTENDEE properties MUST be supplied as appropriate. For new components such as VPOLL, defined here, only PARTICIPANT components MUST be used.

Note that extensions to the <<RFC5546>> specification for VPOLL will be dealt with in later sections.

A participant object that takes part in group scheduling MUST have the following characteristics:

* It MUST have a calendar address (<<RFC5545>> CALENDAR-ADDRESS, <<RFC8984>> calendarAddress).
* It must have one or more scheduling role defined. (PARTICIPANT-TYPE or <<RFC8984>> role)

Scheduling with PARTICIPANT components behaves exactly as with ATTENDEE and ORGANIZER properties. When iTip specifies the setting of ATTENDEE or ORGANIZER parameters then the appropriate PARTICIPANT property will be set.

[[attendee-params]]
=== Attendee parameters mapping

[cols="a,a,a",options="header"]
|===
| Parameter
| iCalendar PARTICIPANT
| jscalendar participant

| CN | NAME (defined 7986) | name

| CUTYPE | KIND (defined here)| kind

| DELEGATED-FROM | PARTICIPATION-DELEGATED-FROM <<new-prop-participation-delegated-from>> | delegatedFrom

| DELEGATED-TO | PARTICIPATION-DELEGATED-TO (Defined here) | delegatedTo

| DIR | LINK <<RFC9253>> | links <<RFC8984>>

| LANGUAGE | LANG (defined here) | language

| MEMBER | MEMBER-OF (defined here)| memberOf

| PARTSTAT | PARTICIPATION-STATUS (defined here)| MEMBER

| ROLE | PARTICIPATION-TYPE (Updated here) | roles

| RSVP | EXPECT-REPLY (Defined here) | expectReply

| SENT-BY | |


|===

