
[appendix,obligation=informative]
== Open issues

public-comment: Not documented and was a parameter on something.
Really sounds like a PARTICIPANT or VOTE property

Notifications: Need to do a section on what Notifications to
  support. +
  A.  VPOLL is about to end and you haven't voted on it yet.
  Instead reuse VALARMS to notify the user?

Future: Restarting a confirmed/completed VPOLL  What to do with
  changes to STATUS:CONFIRMED?  Allow them or not?  What do to that
  poll had a winning event or todo.
  Stress VPOLL UID MUST be unique
  Changing status back from CONFIRMED MUST adjust status of any
  events booked as a result of confirmation.
  MUST winning event be cancelled for POLL-MODE basic?  No - voter
  has indicated now unable to attend - want to revote

Future: Voting on a confirmed/completed VPOLL  Can a voter vote after
  completion?  May be unable to attend and wants to indicate.
  Requires retention of VPOLL
  retention period
  Removed status

ORGANIZER/ATTENDEE validity  Can a user create a poll with scheduled
  events where that user's isn't the organizer of the poll?  So is
  there a requirement that the account that poll is on is able to
  create each one of the resources in the poll? i.e. I can't create
  a poll with a set of events where I am just the attendee of the
  events.  Are there any other restrictions for components in a
  VPOLL?
  Add to security consideration

Update to existing event after poll confirm  When voting on existing
  event - winning properties ONLY are merged in to the real event.

=== Advertising tasks

Use VPOLL for advertising a task to a pool of possible ATTENDEEs and then select the respondent to assign one or more assignees.

Introduce POLL-MODE:ASSIGNMENT

Need to indicate number of assignees required.

Potentially different types of response e.g. ACCEPT or DECLINE, or a weighting e.g. 0 - 100

Take into FREEBUSY discussion.


Need to write down what isn't valid in a VPOLL +
  a.  Can't change POLL-MODE

Guide for ATTENDEE roles
  chair, NON-PARTICIPANT etc

? - some iTip notes  On confirm - send itip if appropriate (PUBLISH)
  - all non-participating - shared - feeds
  Organizer can specify where result is?
  Confirm can specify that itip is sent - ITIP / NONE - parameter ?
  on POLL-WINNER

Need to add example of freebusy in response

[source]
----
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//BedeworkCaldavTest//BedeworkCaldavTest
METHOD: REPLY
BEGIN:VPOLL
BEGIN:PARTICIPANT
PARTICIPANT-TYPE: OWNER
CALENDAR-ADDRESS:mailto:douglm@mysite.edu
UID:schedpart-1234567890
DTSTAMP:20120101T010000Z
SEQUENCE:0
SUMMARY:What to do this week
BEGIN:VFREEBUSY
.......
END:VFREEBUSY
END:PARTICIPANT
BEGIN:PARTICIPANT
PARTICIPANT-TYPE: VOTER
CALENDAR-ADDRESS:mailto:eric@example.com
UID:schedpart-0987654321
DTSTAMP:20120101T010000Z
SEQUENCE:0
SUMMARY:What to do this week
BEGIN:VFREEBUSY
.......
END:VFREEBUSY
END:PARTICIPANT
END:VPOLL
END:VCALENDAR
----
